# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Croptop < Formula
  desc "Publish websites peer to peer"
  homepage "https://crop.top"
  version "0.13.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mejango/croptop/releases/download/v0.13.13/croptop_0.13.13_darwin_amd64.tar.gz"
      sha256 "36f2270968b691a7e27533bdf6f9bccfe9980aa59b3bfcde66abf5ac95e71702"

      define_method(:install) do
        bin.install "croptop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mejango/croptop/releases/download/v0.13.13/croptop_0.13.13_darwin_arm64.tar.gz"
      sha256 "9fa68bdd7206c0e626102faf6fa76b1f5ad5dbcff8cdb55f00ef6817d3ad576e"

      define_method(:install) do
        bin.install "croptop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mejango/croptop/releases/download/v0.13.13/croptop_0.13.13_linux_amd64.tar.gz"
      sha256 "106f984e0c680ddd78f32195cea0cbca4e431a497cf51157685b78cecde5489c"
      define_method(:install) do
        bin.install "croptop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mejango/croptop/releases/download/v0.13.13/croptop_0.13.13_linux_arm64.tar.gz"
      sha256 "a7cd4f0dd5d02d12a4c294a30b7bd6dd635998d48fecae849884c5790c1acaea"
      define_method(:install) do
        bin.install "croptop"
      end
    end
  end

  test do
    system "#{bin}/croptop", "version"
  end
end
